# Generated by Django 4.2.3 on 2023-07-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_client_mobile_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(max_length=11, unique=True),
        ),
    ]
